### ISSUE TITLE
[Feature Request] Add support for `--onevent` flag of librespot

### ISSUE THREAD

**Issue by QuadratClown** [GioF71/librespot-docker#91]
**Is your feature request related to a problem? Please describe.**

`librespot` supports executing custom scripts when events occur, such as a `session_connect` event. This can be configured via the `--onevent` flag, which is not currently supported by the `run-librespot.sh` entrypoint script of `librespot-docker`.

`onevent` scripts can be extremely useful, especially when integrating a `librespot` solution into an external system, such as homeassistant, because it allows triggering other events dependent on the state of the Spotify connect reciever.

**Describe the solution you'd like**

Add `ON_EVENT=<command>` configuration option that, if set, directly corresponds to the `--onevent <command>` flag by `Dockerfile` and `run-librespot`.

The necessary changes are already on this fork:
https://github.com/GioF71/librespot-docker/compare/main...QuadratClown:librespot-docker:main

**Additional context**

The most common usecase of the `onevent` callback is to post the current state of the `librespot` instance to an external server.
Since the base-image has `curl` installed, this can easily be done by executing
```bash
curl -X POST \
-s \
-H "Content-Type: application/json" \
-d '{
    "PLAYER_EVENT": "'"$PLAYER_EVENT"'",
    "TRACK_ID": "'"$TRACK_ID"'",
    "URI": "'"$URI"'",
    "NAME": "'"$NAME"'",
    "COVERS": "'"${COVERS//$'\n'/,}"'",
    "LANGUAGE": "'"$LANGUAGE"'",
    "DURATION_MS": "'"$DURATION_MS"'",
    "NAME": "'"$NAME"'",
    "IS_EXPLICIT": "'"$IS_EXPLICIT"'",
    "ITEM_TYPE": "'"$ITEM_TYPE"'",
    "ARTISTS": "'"$ARTISTS"'",
    "ALBUM_ARTISTS": "'"$ALBUM_ARTISTS"'",
    "ALBUM": "'"$ALBUM"'",
    "NUMBER": "'"$NUMBER"'",
    "DISC_NUMBER": "'"$DISC_NUMBER"'",
    "DESCRIPTION": "'"$DESCRIPTION"'",
    "PUBLISH_TIME": "'"$PUBLISH_TIME"'",
    "SHOW_NAME": "'"$SHOW_NAME"'",
    "POSITION_MS": "'"$POSITION_MS"'",
    "CONNECTION_ID": "'"$CONNECTION_ID"'",
    "USER_NAME": "'"$USER_NAME"'",
    "CLIENT_ID": "'"$CLIENT_ID"'",
    "CLIENT_NAME": "'"$CLIENT_NAME"'",
    "CLIENT_BRAND_NAME": "'"$CLIENT_BRAND_NAME"'",
    "CLIENT_MODEL_NAME": "'"$CLIENT_MODEL_NAME"'",
    "VOLUME": "'"$VOLUME"'",
    "SHUFFLE": "'"$SHUFFLE"'",
    "REPEAT": "'"$REPEAT"'",
    "AUTO_PLAY": "'"$AUTO_PLAY"'",
    "FILTER": "'"$FILTER"'",
    "SINK_STATUS": "'"$SINK_STATUS"'"
}' \
<server-endpoint-url>
```
This command will POST all available values to the endpoint given at `<server-endpoint-url>`.

It might even make sense to directly embed this into a script in `app/bin` and add another config option (such as `ONEVENT_POST_ENDPOINT` to set the `--onevent` flag accordingly.

**Comment by QuadratClown** [comment]
Thanks for the quick reply! I will implement this and create the PR :)

**Comment by GioF71** [comment]
> Thanks for the quick reply! I will implement this and create the PR :)

No please, thank you for your effort and contribution. Will be waiting for the PR!

**Comment by GioF71** [comment]
Hello, I created the [release](https://github.com/GioF71/librespot-docker/releases/tag/release%2F2024-11-17). I think we can close this. Thank you again for your contribution.
